<?php
    if(isset($_REQUEST['var_spa_batch']) && isset($_REQUEST['var_spa_gen_by']) && isset($_REQUEST['var_spa_gen_on']) && isset($_REQUEST['var_spa_user_Id'])){
        security_printing_authorization(trim($_REQUEST['var_spa_batch']),trim($_REQUEST['var_spa_gen_by']),trim($_REQUEST['var_spa_gen_on']),trim($_REQUEST['var_spa_user_Id']));
    }
     if(isset($_REQUEST['get_var_aa']) && isset($_REQUEST['get_var_bb']) && isset($_REQUEST['get_var_ee']) && isset($_REQUEST['get_var_ff']) && isset($_REQUEST['get_var_user'])){
        security_printing_authorization_gried(trim($_REQUEST['get_var_aa']),trim($_REQUEST['get_var_bb']),trim($_REQUEST['get_var_ee']),trim($_REQUEST['get_var_ff']),trim($_REQUEST['get_var_user']));
    }
    
function DatabaseConnection(){
    $conn = mysqli_connect("localhost","root","1234","cdberp");
    return $conn;
}
function security_printing_authorization($var_spa_batch,$var_spa_gen_by,$var_spa_gen_on,$userID){
    $conn = DatabaseConnection();
    echo "<div style='margin-left: 50px;'>
            <input class='buttonManage' style='width: 100px;' type='button' name='btnClose' id='btnClose' value='Close' onclick='pageClose();'/>
</div><br/>";
    $sql_load_table = "SELECT slb.`TYPE_CODE`,
                                 slb.`AMT_FROM`,
                                 slb.`AMT_TO` ,
                                (SELECT COUNT(*)
                                 FROM `sps_let_gen` t1, `sps_let_batch` st2
                                 where st2.`LET_TYPE` = t1.`LET_TYPE`
								   and st2.`BATCH_NUM` = t1.`BATCH_NUM`
								   and st2.`BATCH_STAT` = 'N'
								   and t1.`BATCH_NUM` = '".$var_spa_batch."'
								   and (t1.`AUTH_1_DATE` = '0000-00-00 00:00:00' OR t1.`AUTH_2_DATE` = '0000-00-00 00:00:00' ) AND t1.`dep_amt` >= slb.`AMT_FROM` AND t1.`dep_amt` <= slb.`AMT_TO`) AS Num_letters
                         FROM `sps_let_amt_slabs` slb WHERE slb.`TYPE_CODE` = 'RLET';";
   // echo $sql_load_table;
    $que_load_table = mysqli_query($conn,$sql_load_table) or die(mysqli_error());
    $rowcount = 0;
    $rowcount = mysqli_num_rows($que_load_table);
    echo "<table border='1' cellpadding='0' cellspacing='0'  id='myTable' style='background:#FFFFFF;text-align:center; font-family:Arial, Helvetica, sans-serif; font-size:12px;margin-left: 50px;'>
   	    <tr style='background-color: #BEBABA;'>
            <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'>Letter Type</span></td>
            <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'>Batch Number</span></td>
            <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'>Generated Date</span></td>
            <td style='width:150px; text-align: left;'><span style='margin-left: 5px;'>Generated By</span></td>
            <td style='width:250px; text-align: left;'><span style='margin-left: 5px;'>Amount Slab</span></td>
            <td style='width:150px; text-align: left;'><span style='margin-left: 5px;'>Entries to Be Auth</span></td>
            
        </tr>";
    if($rowcount == 0){
        echo "<tr id='trsub1' title='1' onclick='' onmouseover='isChangeRowColoerOverSub(title);' onmouseout='isChangeRowColoerDownSub(title);'>
                <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'></span><span style='display: none;'><input type='text' name='txtaa1' id='txtaa1' value='' onkeypress='return disableEnterKey(event)' readonly='readonly' /></span></td>
                <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'></span><span style='display: none;'><input type='text' name='txtbb1' id='txtbb1' value='' onkeypress='return disableEnterKey(event)' readonly='readonly' /></span></td>
                <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'></span><span style='display: none;'><input type='text' name='txtcc1' id='txtcc1' value='' onkeypress='return disableEnterKey(event)' readonly='readonly' /></span></td>
                <td style='width:150px; text-align: left;'><span style='margin-left: 5px;'></span><span style='display: none;'><input type='text' name='txtdd1' id='txtdd1' value='' onkeypress='return disableEnterKey(event)' readonly='readonly' /></span></td>
                <td style='width:250px; text-align: left;'><span style='margin-left: 5px;'></span><span style='display: none;'><input type='text' name='txtee1' id='txtee1' value='' onkeypress='return disableEnterKey(event)' readonly='readonly' /><input type='text' name='txtff1' id='txtff1' value='' onkeypress='return disableEnterKey(event)' readonly='readonly' /></span></td>
                <td style='width:150px; text-align: left;'><span style='margin-left: 5px;'></span><span style='display: none;'><input type='text' name='txtgg1' id='txtgg1' value='' onkeypress='return disableEnterKey(event)' readonly='readonly' /></span></td>
            </tr>";
    }else{
        $x = 0;
        while($res_load_table = mysqli_fetch_array($que_load_table)){
            $x++;
            if($res_load_table[3] != 0){
            echo "<tr id='trsub".$x."' title='".$x."' onclick='getAthGried(title);' onmouseover='isChangeRowColoerOverSub(title);' onmouseout='isChangeRowColoerDownSub(title);'>
                            <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'>".$res_load_table[0]."</span><span style='display: none;'><input type='text' name='txtaa".$x."' id='txtaa".$x."' value='".$res_load_table[0]."' onkeypress='return disableEnterKey(event)' readonly='readonly' /></span></td>
                            <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'>".$var_spa_batch."</span><span style='display: none;'><input type='text' name='txtbb".$x."' id='txtbb".$x."' value='".$var_spa_batch."' onkeypress='return disableEnterKey(event)' readonly='readonly' /></span></td>
                            <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'>".$var_spa_gen_on."</span><span style='display: none;'><input type='text' name='txtcc".$x."' id='txtcc".$x."' value='".$var_spa_gen_on."' onkeypress='return disableEnterKey(event)' readonly='readonly' /></span></td>
                            <td style='width:150px; text-align: left;'><span style='margin-left: 5px;'>".$var_spa_gen_by."</span><span style='display: none;'><input type='text' name='txtdd".$x."' id='txtdd".$x."' value='".$var_spa_gen_by."' onkeypress='return disableEnterKey(event)' readonly='readonly' /></span></td>
                            <td style='width:250px; text-align: left;'><span style='margin-left: 5px;'>".$res_load_table[1]." - ".$res_load_table[2]."</span><span style='display: none;'><input type='text' name='txtee".$x."' id='txtee".$x."' value='".$res_load_table[1]."' onkeypress='return disableEnterKey(event)' readonly='readonly' /><input type='text' name='txtff".$x."' id='txtff".$x."' value='".$res_load_table[2]."' onkeypress='return disableEnterKey(event)' readonly='readonly' /></span></td>
                            <td style='width:150px; text-align: left;'><span style='margin-left: 5px;'>".$res_load_table[3]."</span><span style='display: none;'><input type='text' name='txtgg".$x."' id='txtgg".$x."' value='".$res_load_table[3]."' onkeypress='return disableEnterKey(event)' readonly='readonly' /></span></td>
                        </tr>";
            }
        }
    }
    echo "</table>";
}       

function security_printing_authorization_gried($get_var_aa,$get_var_bb,$get_var_ee,$get_var_ff,$get_var_user){
    $conn = DatabaseConnection();
   
    $que_sel_det = mysqli_query($conn,"SELECT `LET_TYPE`,`BATCH_NUM`,`GEN_BY`,`GEN_DATE` FROM `sps_let_batch` WHERE `BATCH_NUM`='".$get_var_bb."';") or die(mysqli_error());
    while($res_sel_det = mysqli_fetch_assoc($que_sel_det)){
        echo "<div style='font-family:Arial, Helvetica, sans-serif; font-size:12px; margin-left: 50px;'>";
        echo "Letter Type : ".$res_sel_det['LET_TYPE']."<br/><br/>";
        echo "Batch Number : ".$res_sel_det['BATCH_NUM']."<br/><br/>";
        echo "Generated Date / Time : ".$res_sel_det['GEN_DATE']."<br/><br/>";
        echo "Generated By : ".$res_sel_det['GEN_BY']."<br/><br/>";
       
        echo "<input class='buttonManage' style='width: 100px;' type='button' name='btnClose' id='btnClose' value='Close' onclick='pageClose();'/><br/><br/>";
        echo "</div>";
    }
    
     echo "<div style='display: none;'> 
        <input type='text' name='is_var_aa' id='is_var_aa' value='".$get_var_aa."' onkeypress='return disableEnterKey(event)' readonly='readonly' />
        <input type='text' name='is_var_bb' id='is_var_bb' value='".$get_var_bb."' onkeypress='return disableEnterKey(event)' readonly='readonly' />
        <input type='text' name='is_var_ee' id='is_var_ee' value='".$get_var_ee."' onkeypress='return disableEnterKey(event)' readonly='readonly' />
        <input type='text' name='is_var_ff' id='is_var_ff' value='".$get_var_ff."' onkeypress='return disableEnterKey(event)' readonly='readonly' />
        <input type='text' name='is_var_user' id='is_var_user' value='".$get_var_user."' onkeypress='return disableEnterKey(event)' readonly='readonly' />
    </div>";
    echo "<table border='1' cellpadding='0' cellspacing='0'  id='myTable' style='background:#FFFFFF;text-align:center; font-family:Arial, Helvetica, sans-serif; font-size:12px;margin-left: 50px;'>
   	    <tr style='background-color: #BEBABA;'>
            <td style='width:50px; text-align: left;'><span style='margin-left: 5px;'>Seq.</span></td>
            <td style='width:200px; text-align: left;'><span style='margin-left: 5px;'>Deposit /Contract Number</span></td>
            <td style='width:300px; text-align: left;'><span style='margin-left: 5px;'>Deposit /Contract Name</span></td>
            <td style='width:150px; text-align: left;'><span style='margin-left: 5px;'>Deposit Amount</span></td>
            <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'>Maturity Date</span></td>
            <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'>Authorized 1</span></td>
            <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'>Authorized 2</span></td>
            
        </tr>";
    $sql_load_g = "SELECT `DEPOSIT_NUM`, `CL_NAME_1`,`dep_amt`, `MAT_DATE`, `AUTH_1_BY`, `AUTH_2_BY`
                    FROM `sps_let_gen` AS t1
                    WHERE t1.`BATCH_NUM` = '".$get_var_bb."' AND (t1.`dep_amt` BETWEEN '".$get_var_ee."' AND '".$get_var_ff."');";
    $que_load_g = mysqli_query($conn, $sql_load_g) or die(mysqli_error());
    $d = 0;
    while($res_load_g = mysqli_fetch_assoc($que_load_g)){
       $d++;
       echo "<tr>
            <td style='width:50px; text-align: left;'><span style='margin-left: 5px;'>".$d."</span></td>
            <td style='width:200px; text-align: left;'><span style='margin-left: 5px;'>".$res_load_g['DEPOSIT_NUM']."</span></td>
            <td style='width:300px; text-align: left;'><span style='margin-left: 5px;'>".$res_load_g['CL_NAME_1']."</span></td>
            <td style='width:150px; text-align: left;'><span style='margin-left: 5px;'>".$res_load_g['dep_amt']."</span></td>
            <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'>".$res_load_g['MAT_DATE']."</span></td>
            <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'>".$res_load_g['AUTH_1_BY']."</span></td>
            <td style='width:100px; text-align: left;'><span style='margin-left: 5px;'>".$res_load_g['AUTH_2_BY']."</span></td>
            
        </tr>";
    }
    echo "</table>";
}
?>
    
        